export const CASES = [
  {id: "tachy-g-code", note: "29 year old female, nausea vomiting headache. i gave her fluids because tachy. critical G code 25 minute r/a x2.", tier: "other", services: [], expectedMinutes: 25, estimated: true},
  {id: "fluids-reassessment", note: "29F vomiting, tachycardic. Gave fluid boluses and reassessed perfusion twice.", tier: "other", services: [], estimated: true},
  {id: "oral-hydration", note: "Mild tachycardia after walking, settled with rest. Drinking water, no treatment needed.", tier: "none", services: []},
  {id: "no-critical-care", note: "Headache, fluids and metoclopramide. No critical care. Felt better and discharged.", tier: "none", services: []},
  {
    id: "sparse",
    note: "27 year old female, chest pain, 25 minutes.",
    tier: "none",
    services: [],
  },
  {
    id: "colloquial-repair",
    note: "I washed out the 3 cm forearm cut and closed it with five nylon stitches under local lidocaine. Good approximation.",
    tier: "none",
    services: ["laceration"],
  },
  {
    id: "shock-estimate",
    note: "BP 72/40 despite fluid boluses, confused and cool. Started norepi, titrated twice while following perfusion and bedside ultrasound. Rechecked after each change. ICU inserted the central line. 90 minutes in the department overall.",
    tier: "life",
    services: [],
    excludes: ["central_line"],
    allowedPerformed: ["pocus"],
    estimated: true,
  },
  {
    id: "interrupted-resus",
    note: "PIA 14:00. Septic shock. I managed norepinephrine and repeated perfusion assessments from 14:00 to 14:40, except 14:12 to 14:22 when I treated another patient. Returned 15:00 to 15:15 for recurrent hypotension, titrated pressor and reassessed response. These were my active care intervals.",
    tier: "life",
    services: [],
    expectedMinutes: 45,
  },
  {
    id: "respiratory",
    note: "Acute respiratory failure. I started BiPAP and titrated pressures with repeated airway and breathing checks. Exclusive critical care 00:05–00:21; 01:10–01:20; 01:40–01:47. Nursing placed the IV.",
    tier: "life",
    services: [],
    expectedMinutes: 33,
  },
  {
    id: "negative-procedure",
    note: "Small abscess, focused assessment. I offered drainage; patient declined. No procedure performed. No resuscitation. Discharged with follow-up.",
    tier: "none",
    services: [],
    forbiddenPerformed: ["abscess"],
  },
  {
    id: "stable-long-stay",
    note: "Stable chest pain, ECG and troponins reviewed. No ongoing pain or instability. Waited 4 hours for repeat bloodwork. Discharged. Total encounter 5 hours.",
    tier: "none",
    services: [],
  },
  {
    id: "reassessment",
    note: "PIA 09:00 flank pain assessed. At 11:40 I reassessed for persistent severe pain and new vomiting despite initial treatment. Repeat abdominal exam, ordered CT and gave additional IV analgesia. Symptoms improved by 12:10.",
    tier: "none",
    services: [],
    opportunity: "reassessment",
  },
  {
    id: "pressor-shorthand",
    note: "77M febrile, hypotensive, MAP 48 after fluids. Started levophed and adjusted the infusion twice, bedside perfusion checks after each change. I spent 20 minutes actively managing his shock; no start clock recorded.",
    tier: "life",
    services: [],
    estimated: true,
    expectedMinutes: 20,
  },
  {
    id: "waiting-for-ride",
    note: "Near-syncope. BP and examination normal throughout. Felt better after drinking water. Waited two hours for a ride home, no further active care.",
    tier: "none",
    services: [],
  },
  {
    id: "face-repair",
    note: "At 18:10 I infiltrated lidocaine and sewed the 2 cm chin wound with nylon. No other injury. Good approximation.",
    tier: "none",
    services: ["laceration"],
  },
  {
    id: "sedation-role",
    note: "I was the sedation physician only. Gave ketamine and monitored procedural sedation from 14:15 to 14:30. Orthopedics reduced the shoulder. No separate assessment by me.",
    tier: "none",
    services: [],
    excludes: ["dislocation"],
  },
];
